version: '3.2'
services:

  broker:
    image: confluentinc/cp-kafka:7.5.0
    hostname: broker
    container_name: 'broker'
    restart: always
    ports:
      - 9093:9093
      - 39093:39093
    extra_hosts:
      - host.docker.internal:host-gateway
    environment:
      CLUSTER_ID: kafka-docker-cluster-1
      KAFKA_INTER_BROKER_LISTENER_NAME: DOCKER_LISTENERS
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LISTENERS: DOCKER_LISTENERS://:9093,CONTROLLER://:9093,HOST_MACHINE_LISTENERS://:39093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: CONTROLLER:PLAINTEXT,DOCKER_LISTENERS:PLAINTEXT,HOST_MACHINE_LISTENERS:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: DOCKER_LISTENERS://host.docker.internal:9093,HOST_MACHINE_LISTENERS://127.0.0.1:39093 #This works for the Scala App from intellij if set to use 127.0.0.1
      KAFKA_BROKER_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@127.0.0.1:9093
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_CREATE_TOPICS: "car_control:1:1,topic2:1:1,topic3:1:1"
